# Created with YamlCreate.ps1 v2.1.0 $debug=NVS1.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: TestPackage.TestApp
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://drive.google.com/file/d/1Y1YoHdh8VMwhWI0xsxH67UMY_OJM4GQl/view?usp=sharing
  InstallerSha256: E808B4F8C761B8BE2272596E508258EAEFBC2F6D524DB23E7C526A2D6B3B69B1
ManifestType: installer
ManifestVersion: 1.1.0
